name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, macOS-latest]


    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install iniparser
#     - name: make clean
#       run: make clean
#     - name: make
#       run: make
#     - name: make distcheck
#       run: make distcheck
